Repository ArtLable/back-end, pull requests merged in 2023-09, with the labels that each got.

#5 [FEATURE][COMMON] 각종 Configuration 생성
  build.gradle
  src/main/java/com/artlable/backend/common/ResponseMessage.java
  src/main/java/com/artlable/backend/config/BeanConfiguration.java
  src/main/java/com/artlable/backend/config/JPAConfiguration.java
  src/main/java/com/artlable/backend/config/SecurityConfig.java
  src/main/java/com/artlable/backend/config/SwaggerConfig.java
  src/main/java/com/artlable/backend/config/WebConfig.java
  src/main/java/com/artlable/backend/exception/ApiExceptionDTO.java
  src/main/java/com/artlable/backend/exception/TokenException.java
  src/main/java/com/artlable/backend/feed/command/application/controller/Controller.java
  src/main/java/com/artlable/backend/feed/command/application/dto/DTO.java
  src/main/java/com/artlable/backend/feed/command/application/service/Service.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/Repository.java
  src/main/java/com/artlable/backend/feed/command/domain/service/Service.java
  src/main/java/com/artlable/backend/feed/command/infra/repository/Repository.java
  src/main/java/com/artlable/backend/feed/command/infra/service/Service.java
  src/main/java/com/artlable/backend/feed/query/application/controller/Controller.java
  src/main/java/com/artlable/backend/feed/query/application/dto/DTO.java
  src/main/java/com/artlable/backend/feed/query/application/service/Service.java
  src/main/java/com/artlable/backend/feed/query/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/feed/query/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/feed/query/domain/repository/Repository.java
  src/main/java/com/artlable/backend/feed/query/domain/service/Service.java
  src/main/java/com/artlable/backend/feed/query/infra/repository/Repository.java
  src/main/java/com/artlable/backend/feed/query/infra/service/Service.java
Labels: feature

#16 [FEATURE][Common] Entity2 구현
  src/main/java/com/artlable/backend/comment/command/domain/aggregate/entity/CommentEntity.java
  src/main/java/com/artlable/backend/common/AuditingFields.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/FeedEntity.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/SaveFeed.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/entity/FileEntity.java
  src/main/java/com/artlable/backend/like/command/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/like/command/domain/aggregate/entity/LikeEntity.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/ReportEntity.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/enumtype/ReportStateEnum.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/enumtype/ReportTypeEnum.java
Labels: feature

#17 Refactor/member/entity개선
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/MemberEntity.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberAgeRange.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberGender.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberRole.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberSocialLogin.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/member/command/domain/repository/MemberRepository.java
  src/main/java/com/artlable/backend/member/command/domain/repository/Repository.java
Labels: refactor

#20 [FEATURE][FEED] CRUD 컨트롤러 구현
  build.gradle
  src/main/java/com/artlable/backend/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/com/artlable/backend/common/ResponseMessage.java
  src/main/java/com/artlable/backend/feed/command/application/controller/Controller.java
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/DTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedDeleteDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedListDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedRegistDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedSearchFilter.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedUpdateDTO.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/application/service/Service.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/FeedEntity.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedMapper.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedRepository.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/Repository.java
  src/main/java/com/artlable/backend/feed/command/domain/service/Service.java
  src/main/java/com/artlable/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/artlable/backend/file/command/application/service/FileService.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/entity/File.java
  src/main/java/com/artlable/backend/like/command/domain/aggregate/entity/Like.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/ReportEntity.java
  src/main/java/com/artlable/backend/savefeed/SaveFeed.java
Labels: feature

#21 [REFACTOR][MEMBER] ENTITY 개선
  build.gradle
  src/main/java/com/artlable/backend/common/page/Pagenation.java
  src/main/java/com/artlable/backend/common/page/PagingButtonInfo.java
  src/main/java/com/artlable/backend/config/BeanConfiguration.java
  src/main/java/com/artlable/backend/jwt/TokenProvider.java
  src/main/java/com/artlable/backend/member/command/application/controller/Controller.java
  src/main/java/com/artlable/backend/member/command/application/controller/MemberController.java
  src/main/java/com/artlable/backend/member/command/application/dto/CreateMemberLocalDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/DTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/UpdateMemberLocalDTO.java
  src/main/java/com/artlable/backend/member/command/application/service/CreateMemberService.java
  src/main/java/com/artlable/backend/member/command/application/service/Service.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Auth.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/artlable/backend/member/command/domain/service/Service.java
  src/main/java/com/artlable/backend/member/command/infra/repository/Repository.java
  src/main/java/com/artlable/backend/member/command/infra/service/Service.java
  src/main/resources/application.yml
Labels: refactor

#23 [FEATURE][FEED] CRUD 컨트롤러 수정 및 서비스 수정
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedDeleteDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedRegistDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedSearchFilter.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedUpdateDTO.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/ResponseMessage.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedMapper.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedRepository.java
  src/main/java/com/artlable/backend/feed/command/domain/service/Service.java
  src/test/java/com/artlable/backend/feed/FeedServiceTests.java
Labels: feature

#25 [FEATURE][FEED] 서비스 및 레퍼지토리 수정
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedRepository.java
Labels: feature

#26 [FEATURE][FEED] 엔티티 및 DTO 수정
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedDeleteDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedListDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedRegistDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedUpdateDTO.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
Labels: feature

#27 [FEATURE][MEMBER]crud구현 초안
  build.gradle
  src/main/java/com/artlable/backend/config/JwtConfig.java
  src/main/java/com/artlable/backend/config/SecurityConfig.java
  src/main/java/com/artlable/backend/config/SwaggerConfig.java
  src/main/java/com/artlable/backend/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/artlable/backend/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/artlable/backend/jwt/JwtFilter.java
  src/main/java/com/artlable/backend/jwt/TokenProvider.java
  src/main/java/com/artlable/backend/login/command/application/controller/Controller.java
  src/main/java/com/artlable/backend/login/command/application/controller/LoginController.java
  src/main/java/com/artlable/backend/login/command/application/service/LoginService.java
  src/main/java/com/artlable/backend/login/command/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/login/command/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/login/command/domain/repository/LoginRepository.java
  src/main/java/com/artlable/backend/login/command/domain/service/Service.java
  src/main/java/com/artlable/backend/login/command/infra/repository/Repository.java
  src/main/java/com/artlable/backend/login/command/infra/service/Service.java
  src/main/java/com/artlable/backend/login/query/application/controller/Controller.java
  src/main/java/com/artlable/backend/login/query/application/dto/DTO.java
  src/main/java/com/artlable/backend/login/query/application/service/Service.java
  src/main/java/com/artlable/backend/login/query/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/login/query/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/login/query/domain/repository/Repository.java
  src/main/java/com/artlable/backend/login/query/domain/service/Service.java
  src/main/java/com/artlable/backend/login/query/infra/repository/Repository.java
  src/main/java/com/artlable/backend/login/query/infra/service/Service.java
  src/main/java/com/artlable/backend/member/command/application/controller/MemberController.java
  src/main/java/com/artlable/backend/member/command/application/dto/CreateMemberLocalDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/CustomUserDetails.java
  src/main/java/com/artlable/backend/member/command/application/dto/UpdateMemberLocalDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/auth/AuthRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/auth/AuthResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/login/LoginRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/login/LoginResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/sign/SignRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/sign/SignResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/service/CreateMemberService.java
  src/main/java/com/artlable/backend/member/command/application/service/JpaUserDetailsService.java
  src/main/java/com/artlable/backend/member/command/application/service/SignService.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Authority.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberAgeRange.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberGender.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberRole.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/enumvalue/MemberSocialLogin.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/artlable/backend/member/command/domain/repository/MemberRepository.java
  src/main/resources/application.yml
Labels: feature

#30 [FEATURE][WEBTOON][NOBLE] 엔티티 구현
  src/main/java/com/artlable/backend/noble/command/domain/aggregate/entity/Noble.java
  src/main/java/com/artlable/backend/webtoon/command/domain/aggregate/entity/WebToon.java
Labels: feature

#31 [FEATURE][LOGIN] CRUD 컨트롤러 구현
  src/main/java/com/artlable/backend/common/CustomUserDetails.java
  src/main/java/com/artlable/backend/common/JpaUserDetailsService.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/artlable/backend/login/command/application/controller/LoginController.java
  src/main/java/com/artlable/backend/login/command/application/dto/login/LoginResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/controller/LoginController.java
  src/main/java/com/artlable/backend/member/command/application/controller/MemberController.java
  src/main/java/com/artlable/backend/member/command/application/dto/auth/AuthResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/login/LoginRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/login/LoginResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/sign/SignRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/sign/SignResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/update/UpdateInfoRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/update/UpdatePwdRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/service/LoginService.java
  src/main/java/com/artlable/backend/member/command/application/service/SignService.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Authority.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/artlable/backend/member/command/domain/repository/AuthorityRepository.java
  src/main/java/com/artlable/backend/member/command/domain/repository/LoginRepository.java
  src/main/java/com/artlable/backend/member/command/domain/repository/MemberRepository.java
  src/main/java/com/artlable/backend/member/query/application/controller/Controller.java
  src/main/java/com/artlable/backend/member/query/application/dto/DTO.java
  src/main/java/com/artlable/backend/member/query/application/service/Service.java
  src/main/java/com/artlable/backend/member/query/domain/aggregate/entity/Entity.java
  src/main/java/com/artlable/backend/member/query/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/member/query/domain/repository/Repository.java
  src/main/java/com/artlable/backend/member/query/domain/service/Service.java
  src/main/java/com/artlable/backend/member/query/infra/repository/Repository.java
  src/main/java/com/artlable/backend/member/query/infra/service/Service.java
  src/test/java/com/artlable/backend/member/command/application/service/LoginServiceTests.java
Labels: feature

#32 [FEATURE][FILE]서비스 및 컨트롤러 구현
  src/main/java/com/artlable/backend/config/SecurityConfig.java
  src/main/java/com/artlable/backend/file/command/application/controller/Controller.java
  src/main/java/com/artlable/backend/file/command/application/controller/FileController.java
  src/main/java/com/artlable/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/entity/File.java
  src/main/java/com/artlable/backend/file/command/domain/repository/FileRepository.java
  src/main/java/com/artlable/backend/file/command/domain/repository/Repository.java
  src/main/java/com/artlable/backend/noble/command/domain/aggregate/entity/Noble.java
  src/main/java/com/artlable/backend/webtoon/command/domain/aggregate/entity/WebToon.java
Labels: feature

#38 [REFACTOR][COMMON] 공통사용로직 최적화
  README.md
  src/main/java/com/artlable/backend/comment/command/application/controller/CommentController.java
  src/main/java/com/artlable/backend/comment/command/application/dto/CommentCreateDTO.java
  src/main/java/com/artlable/backend/comment/command/application/dto/CommentUpdateDTO.java
  src/main/java/com/artlable/backend/comment/command/application/service/CommentService.java
  src/main/java/com/artlable/backend/comment/command/application/service/Service.java
  src/main/java/com/artlable/backend/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/com/artlable/backend/comment/command/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/comment/command/domain/repository/CommentRepository.java
  src/main/java/com/artlable/backend/comment/command/domain/repository/Repository.java
  src/main/java/com/artlable/backend/common/ResponseMessage.java
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedDeleteDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedListDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedRegistDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedSearchFilter.java
  src/main/java/com/artlable/backend/feed/command/application/dto/FeedUpdateDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/create/FeedCreateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/read/FeedReadResponseDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/update/FeedUpdateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/ResponseMessage.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedMapper.java
  src/main/java/com/artlable/backend/feed/command/domain/repository/FeedRepository.java
  src/main/java/com/artlable/backend/file/command/application/controller/FileController.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/entity/File.java
  src/main/java/com/artlable/backend/jwt/TokenProvider.java
  src/main/java/com/artlable/backend/like/command/domain/aggregate/entity/Like.java
  src/main/java/com/artlable/backend/member/command/application/controller/LoginController.java
  src/main/java/com/artlable/backend/member/command/application/controller/MemberController.java
  src/main/java/com/artlable/backend/member/command/application/dto/auth/AuthResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/login/LoginRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/login/LoginResponseDTO.java
  src/main/java/com/artlable/backend/member/command/application/service/LoginService.java
  src/main/java/com/artlable/backend/member/command/application/service/SignService.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/artlable/backend/member/command/domain/repository/AuthorityRepository.java
  src/main/java/com/artlable/backend/member/command/domain/repository/MemberRepository.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/enumvalue/ReportState.java
  src/main/java/com/artlable/backend/report/command/domain/aggregate/entity/enumvalue/ReportTypeEnum.java
Labels: feature, refactor

#39 [FEATURE][FILE]서비스 및 컨트롤러 수정
  build.gradle
  src/main/java/com/artlable/backend/common/annotation/InfraAnnotation.java
  src/main/java/com/artlable/backend/config/FileWebConfig.java
  src/main/java/com/artlable/backend/config/WebClientConfig.java
  src/main/java/com/artlable/backend/config/WebConfig.java
  src/main/java/com/artlable/backend/file/command/application/controller/FileController.java
  src/main/java/com/artlable/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/artlable/backend/file/command/application/dto/FileListReqeust.java
  src/main/java/com/artlable/backend/file/command/application/dto/FileResponse.java
  src/main/java/com/artlable/backend/file/command/application/dto/SingleFileRequest.java
  src/main/java/com/artlable/backend/file/command/application/service/FileService.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/vo/MemberVo.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/vo/Vo.java
  src/main/java/com/artlable/backend/file/command/domain/service/FileDomainService.java
  src/main/java/com/artlable/backend/file/command/infra/service/FileInfraService.java
  src/main/java/com/artlable/backend/file/command/infra/service/HttpPostMultipart.java
  src/main/resources/static/properties/image.properties
Labels: feature

#40 [REFACTOR][COMMON] CRUD Auth 구조개선(HOTFIX)
  src/main/java/com/artlable/backend/common/ResponseMessage.java
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/file/command/domain/aggregate/entity/File.java
  src/main/java/com/artlable/backend/member/command/application/controller/LoginController.java
  src/main/java/com/artlable/backend/member/command/application/controller/MemberController.java
  src/main/java/com/artlable/backend/member/command/application/dto/update/UpdateInfoRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/update/UpdatePwdRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/service/LoginService.java
  src/main/java/com/artlable/backend/member/command/application/service/SignService.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
Labels: feature, refactor

#41 Feature/file/service/controller 수정
  src/main/java/com/artlable/backend/common/annotation/DomainAnnotation.java
  src/main/java/com/artlable/backend/common/response/ApiResponse.java
  src/main/java/com/artlable/backend/common/response/enumtype/ApiStatus.java
  src/main/java/com/artlable/backend/file/command/application/dto/AllFileResponse.java
Labels: feature

#43 [FEATURE][FILE]CRUD,Service구현
  src/main/java/com/artlable/backend/config/FileWebConfig.java
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/artlable/backend/files/command/application/controller/FilesController.java
  src/main/java/com/artlable/backend/files/command/application/service/FileService.java
  src/main/java/com/artlable/backend/files/command/domain/aggregate/entity/Files.java
  src/main/java/com/artlable/backend/member/command/application/controller/LoginController.java
  src/main/java/com/artlable/backend/member/command/domain/aggregate/entity/Member.java
Labels: feature

#45 [FEATURE][NOVEL][NOVEL CHARACTER][NOVEL SUMMARY] CRUD 구현
  src/main/java/com/artlable/backend/feed/command/application/dto/create/FeedCreateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/read/FeedReadResponseDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/update/FeedUpdateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/application/service/FeedService.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/artlable/backend/files/command/application/dto/FileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/FileResponseDTO.java
  src/main/java/com/artlable/backend/noble/command/application/controller/NovelCharacterController.java
  src/main/java/com/artlable/backend/noble/command/application/controller/NovelController.java
  src/main/java/com/artlable/backend/noble/command/application/controller/NovelSummaryController.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novel/NovelCreate.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novel/NovelRead.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novel/NovelUpdate.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novelcharacter/NovelCreateCharacter.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novelcharacter/NovelReadCharacter.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novelcharacter/NovelUpdateCharacter.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novelsummary/NovelCreateSummary.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novelsummary/NovelReadSummary.java
  src/main/java/com/artlable/backend/noble/command/application/dto/novelsummary/NovelUpdateSummary.java
  src/main/java/com/artlable/backend/noble/command/domain/aggregate/entity/Noble.java
  src/main/java/com/artlable/backend/noble/command/domain/aggregate/entity/Novel.java
  src/main/java/com/artlable/backend/noble/command/domain/aggregate/entity/NovelCharacter.java
  src/main/java/com/artlable/backend/noble/command/domain/aggregate/entity/NovelSummary.java
  src/main/java/com/artlable/backend/noble/command/domain/repository/NovelCharacterRepository.java
  src/main/java/com/artlable/backend/noble/command/domain/repository/NovelRepository.java
  src/main/java/com/artlable/backend/noble/command/domain/repository/NovelSummaryRepository.java
  src/main/java/com/artlable/backend/noble/command/domain/service/NovelCharacterService.java
  src/main/java/com/artlable/backend/noble/command/domain/service/NovelService.java
  src/main/java/com/artlable/backend/noble/command/domain/service/NovelSummaryService.java
Labels: feature

#47 [FEATURE][FEED]CRUD+File구현
  build.gradle
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/create/FeedCreateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/read/FeedReadResponseDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/update/FeedUpdateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/artlable/backend/files/command/application/dto/CreateFeedFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/ReadFeedFileResponseDTO.java
  src/main/java/com/artlable/backend/files/command/application/service/FileService.java
  src/main/java/com/artlable/backend/files/command/domain/aggregate/entity/Files.java
  src/main/java/com/artlable/backend/member/command/application/controller/MemberController.java
  src/main/java/com/artlable/backend/member/command/application/dto/update/UpdateInfoRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/dto/update/UpdatePwdRequestDTO.java
  src/main/java/com/artlable/backend/member/command/application/service/SignService.java
Labels: feature

#48 Feature/common/novel,webtoon외부api
  src/main/java/com/artlable/backend/common/ResponseMessage.java
  src/main/java/com/artlable/backend/config/WebConfig.java
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/update/FeedUpdateRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/service/FileService.java
  src/main/java/com/artlable/backend/novel/command/infra/repository/Repository.java
  src/main/java/com/artlable/backend/novel/command/infra/service/Service.java
  src/main/java/com/artlable/backend/webtoon/command/application/service/LearningService.java
  src/main/java/com/artlable/backend/webtoon/command/infra/repository/Repository.java
  src/main/java/com/artlable/backend/webtoon/command/infra/service/WebtoonAiService.java
Labels: feature

#49 [FEATURE][NOVEL]read 수정
  src/main/java/com/artlable/backend/config/SecurityConfig.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelCharacterController.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelController.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelSummaryController.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novel/NovelCreate.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novel/NovelRead.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelCreateCharacter.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelReadCharacter.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelUpdateCharacter.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelresult/NovelReadResult.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelsummary/NovelCreateSummary.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelsummary/NovelReadSummary.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelsummary/NovelUpdateSummary.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/Novel.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelCharacter.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelResult.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelSummary.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelCharacterService.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelService.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelSummaryService.java
Labels: feature

#50 Feature/common/novel,webtoon외부api
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/files/command/application/service/FileService.java
  src/main/java/com/artlable/backend/files/command/domain/aggregate/entity/Files.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelCharacterController.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelController.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novel/NovelCreateDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novel/NovelReadDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novel/NovelUpdateDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelCreateCharacterDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelReadCharacterDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelUpdateCharacterDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelresult/NovelReadResult.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelresult/NovelReadResultDTO.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/Novel.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelResult.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelSummary.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelCharacterService.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelService.java
Labels: feature

#51 Feature/file/수정
  src/main/java/com/artlable/backend/common/Base64ToFile.java
  src/main/java/com/artlable/backend/config/SecurityConfig.java
  src/main/java/com/artlable/backend/feed/command/application/controller/FeedController.java
  src/main/java/com/artlable/backend/feed/command/application/dto/create/FeedCreateRequestDTO.java
  src/main/java/com/artlable/backend/feed/command/application/dto/read/FeedReadResponseDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/feed/CreateFeedFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/feed/ReadFeedFileResponseDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/novel/CreateNovelSummaryFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/novel/ReadNovelFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/webtoon/CreateWebtoonLerningFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/dto/webtoon/ReadNovelFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/service/FileService.java
  src/main/java/com/artlable/backend/files/command/domain/aggregate/entity/Files.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelCharacterController.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelController.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelSummaryController.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novel/NovelReadDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelcharacter/NovelReadCharacterDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelresult/NovelReadResultDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelsummary/NovelCreateSummaryDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelsummary/NovelReadSummaryDTO.java
  src/main/java/com/artlable/backend/novel/command/application/dto/novelsummary/NovelUpdateSummaryDTO.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/Novel.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelCharacter.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelResult.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelSummaryService.java
  src/main/java/com/artlable/backend/webtoon/command/application/controller/InferenceController.java
  src/main/java/com/artlable/backend/webtoon/command/application/controller/LearningController.java
  src/main/java/com/artlable/backend/webtoon/command/application/dto/inference/InferenceCreateDTO.java
  src/main/java/com/artlable/backend/webtoon/command/application/dto/inference/InferenceReadDTO.java
  src/main/java/com/artlable/backend/webtoon/command/application/dto/inference/InferenceUpdateDTO.java
  src/main/java/com/artlable/backend/webtoon/command/application/dto/learning/LearningCreateDTO.java
  src/main/java/com/artlable/backend/webtoon/command/application/dto/learning/LearningReadDTO.java
  src/main/java/com/artlable/backend/webtoon/command/application/dto/learning/LearningUpdateDTO.java
  src/main/java/com/artlable/backend/webtoon/command/application/service/InferenceService.java
  src/main/java/com/artlable/backend/webtoon/command/application/service/LearningService.java
  src/main/java/com/artlable/backend/webtoon/command/domain/aggregate/entity/Learning.java
  src/main/java/com/artlable/backend/webtoon/command/infra/service/BASE64DecodedMultipartFile.java
  src/main/java/com/artlable/backend/webtoon/command/infra/service/InferenceWebtoonService.java
  src/main/java/com/artlable/backend/webtoon/command/infra/service/LearningWebtoonService.java
Labels: feature

#52 [FEATURE][COMMON]소설 연결
  src/main/java/com/artlable/backend/config/SecurityConfig.java
  src/main/java/com/artlable/backend/files/command/application/dto/webtoon/CreateWebtoonLerningFileRequestDTO.java
  src/main/java/com/artlable/backend/files/command/application/service/FileService.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelController.java
  src/main/java/com/artlable/backend/novel/command/application/controller/NovelSummaryController.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/Novel.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelCharacter.java
  src/main/java/com/artlable/backend/novel/command/domain/aggregate/entity/NovelSummary.java
  src/main/java/com/artlable/backend/novel/command/domain/service/NovelService.java
  src/main/java/com/artlable/backend/webtoon/command/application/service/LearningService.java
Labels: feature
